:_mod-docs-content-type: CONCEPT
include::_attributes/common-attributes.adoc[]
[id="managing-app-sets-in-non-control-plane-namespaces"]
= Manage ApplicationSets

:FeatureName: Argo CD application sets in non-control plane namespaces
By using application sets, you can automate and manage the deployments of multiple Argo CD applications declaratively from a single mono-repository to many clusters at once with greater flexibility.
With {gitops-title} 1.12 and later, as a cluster administrator, you can create and manage `ApplicationSet` resources in non-control plane namespaces other than `openshift-gitops`. To do this, enable and configure the `ArgoCD` and `ApplicationSet` custom resources (CRs). This is useful in multitenancy environments where isolated teams manage their own Argo CD application deployments. In the Argo CD open source project, this is called the _ApplicationSet in any namespace_ feature.
[NOTE]
====
The generated Argo CD applications can create resources in any non-control plane namespace. However, the application itself will be in the same namespace as the application set resources.
====

