:_mod-docs-content-type: CONCEPT
include::_attributes/common-attributes.adoc[]
[id="monitoring-argo-cd-custom-resource-workloads"]
= Monitoring Argo CD custom resource workloads

With {gitops-title}, you can monitor the availability of Argo CD custom resource workloads for specific Argo CD instances. When workload pods for components such as the application controller, repository server, or API server fail to start, or when the number of ready replicas does not match the desired replica count, the {gitops-shortname} Operator triggers alerts. You can enable or disable workload monitoring for individual Argo CD instances.
Before enabling workload monitoring, ensure that you have:

* The monitoring stack configured in your cluster in the `openshift-monitoring` project. In addition, the Argo CD instance is in a namespace that you can monitor through Prometheus.
* The `kube-state-metrics` service is running on your cluster.
* Optional: If you are enabling monitoring for an Argo CD instance already present in a user-defined project, ensure that the monitoring is link:https://docs.openshift.com/container-platform/latest/observability/monitoring/enabling-monitoring-for-user-defined-projects.html#enabling-monitoring-for-user-defined-projects_enabling-monitoring-for-user-defined-projects[enabled for user-defined projects] in your cluster.
+
[NOTE]
====
To monitor an Argo CD instance in a namespace not watched by the default openshift-monitoring stack, enable user workload monitoring. This applies to namespaces that do not start with `openshift-*`. Enabling user workload monitoring allows the monitoring stack to detect the created PrometheusRule.
====

