:_mod-docs-content-type: CONCEPT
include::_attributes/common-attributes.adoc[]
[id="multitenancy-support-in-gitops"]
= Multitenancy support in GitOps

Multitenancy is a software architecture where a single software instance serves many distinct user groups, or tenants. You can share a single Argo CD instance to deploy resources while maintaining isolation between users.
With {gitops-title} Operator on {OCP}, as a cluster administrator, you can give multitenant access to the cluster for application delivery teams (tenants). You can allow tenants to create and manage dedicated Argo CD instances in their user-defined namespaces without having administrative permissions. The tenants have full autonomy and can tailor this instance to their needs and requirements without interfering with other tenants.
[NOTE]
====
For a multitenant cluster, the person managing the Argo CD instance might not be the person who manages the cluster and its users. Therefore, you cannot have the Argo CD Application Controller (`argocd-application-controller` component) as a superuser in the cluster.
====
The Argo CD Application Controller reconciles resources in managed clusters. To use multitenancy in the {gitops-shortname} Operator, configure permissions based on your use cases and tenant requirements. Explicitly grant, extend, or restrict permissions for Argo CD instances, applications, and remote clusters to control operations.
[id="gitops-argocd-instance-scopes_{context}"]
== Argo CD instance scopes
The {gitops-title} Operator creates instances that you can classify broadly into the following modes, all supporting multitenancy:
* Namespace-scoped instance (Application delivery instance)
* Cluster-scoped instance
* Default cluster-scoped instance

