[id="configuring-argocd-gitops-cli"]
= Configuring the GitOps CLI

[IMPORTANT]
====
The GitOps argocd CLI tool is a Technology Preview feature only. Technology Preview features
are not supported with Red Hat production service level agreements (SLAs) and
might not be functionally complete. Red Hat does not recommend using them
in production. These features provide early access to upcoming product
features, enabling customers to test functionality and provide feedback during
the development process.

For more information about the support scope of Red Hat Technology Preview features, see link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Support Scope].
====

You can configure the GitOps `argocd` CLI to enable tab completion.

[id="gitops-argocd-cli-enabling-tab-completion_configuring-argocd-gitops-cli"]
== Enabling tab completion

After you install the GitOps `argocd` CLI, you can enable tab completion to automatically complete `argocd` commands or suggest options when you press Tab.

[NOTE]
====
Tab completions only exist for the Bash shell.
====

.Prerequisites

* You must have the GitOps `argocd` CLI tool installed.
* You must have `bash-completion` installed on your local system.

.Procedure

The following procedure enables tab completion for the Bash shell.

. Save the Bash completion code to a file:
+
[source,terminal]
----
$ argocd completion bash > argocd_bash_completion
----

. Copy the file to `/etc/bash_completion.d/`:
+
[source,terminal]
----
$ sudo cp argocd_bash_completion /etc/bash_completion.d/
----
+
Alternatively, you can save the file to a local directory and source it from your `.bash_profile` file instead.

Tab completion is enabled when you open a new terminal.
